version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_net
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 10

  extractor:
    image: extractor
    container_name: extractor
    environment:
      - BROKER_URL
    build:
      context: ./extractor
    networks:
      - rabbitmq_net
    volumes:
      - ./resources:/extractor/resources
    depends_on:
      rabbitmq:
        condition: service_healthy

  cleaner:
    image: cleaner
    environment:
      - BROKER_URL
    build:
      context: ./cleaner
    networks:
      - rabbitmq_net
    depends_on:
      rabbitmq:
        condition: service_healthy


networks:
  rabbitmq_net:
    driver: bridge