services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
    restart: always

  extractor:
    image: extractor
    container_name: extractor
    environment:
      - BROKER_URL
    build:
      context: ./extractor
    networks:
      - rabbitmq_net
    volumes:
      - ./resources:/extractor/resources
    depends_on:
      - rabbitmq

  cleaner:
    image: cleaner
    container_name: cleaner
    environment:
      - BROKER_URL
    build:
      context: ./cleaner
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq


networks:
  rabbitmq_net:
    driver: bridge